apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: ruby-ex
    app.kubernetes.io/component: ruby-ex
    app.kubernetes.io/instance: ruby-ex
  name: ruby-ex
  namespace: myproject
spec:
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/KadirSoft/ruby-ex.git
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ruby:3.0-ubi9
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: ruby-ex:latest
  triggers:
  - type: GitHub
    github:
      secretReference:
        name: github-webhook-secret
  - type: ConfigChange
  - type: ImageChange
    imageChange: {}
