apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"ruby-ex:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"ruby-ex\")].image"}]'
  labels:
    app: ruby-ex
    app.kubernetes.io/component: ruby-ex
    app.kubernetes.io/instance: ruby-ex
  name: ruby-ex
  namespace: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: ruby-ex
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        deployment: ruby-ex
    spec:
      containers:
      - name: ruby-ex
        image: image-registry.openshift-image-registry.svc:5000/myproject/ruby-ex:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
