apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: ruby-ex
    app.kubernetes.io/component: ruby-ex
    app.kubernetes.io/instance: ruby-ex
  name: ruby-ex
  namespace: myproject
spec:
  lookupPolicy:
    local: false
