apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: ruby-ex
    app.kubernetes.io/component: ruby-ex
    app.kubernetes.io/instance: ruby-ex
  name: ruby-ex
  namespace: myproject
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: ruby-ex
    weight: 100
  wildcardPolicy: None
